#!/bin/bash

#alfred version v1.4.0 -> needs to be changed to the one currently used by refinery if nessecary

echo -ne 'building container...'
docker build -t kernai/alfred:v1.4.0 -f Dockerfile . > /dev/null 2>&1
echo -ne '\t\t [done]\n'

echo -ne 'start refinery like normal (the tag was replaced)'