#!/bin/bash
trap "echo -ne '\nstopping container...' && docker stop alfred > /dev/null 2>&1 && echo -ne '\t\t [done]\n'" EXIT

echo -ne 'stopping old container...'
docker stop alfred > /dev/null 2>&1
echo -ne '\t [done]\n'

echo -ne 'building container...'
docker build -t alfred-dev -f dev.Dockerfile . > /dev/null 2>&1
echo -ne '\t\t [done]\n'

echo -ne 'starting...'
docker run -d --rm \
--name alfred \
-p 7066:80 \
-e POSTGRES=postgresql://postgres:onetask@graphql-postgres:5432 \
--mount type=bind,source="$(pwd)"/,target=/app \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /Users/felixkirsch/Code/refinery/refinery:/refinery \
--network refinery_default \
alfred-dev > /dev/null 2>&1
echo -ne '\t\t\t [done]\n'

docker logs -f alfred
